### ISSUE TITLE
Network Parse Outline

### ISSUE THREAD

**Issue by vl123-ai** [Good-Hair/project-guide#6]
Acceptance Criteria:
Create an account on Hiroku
Set up parse dashboard
Add data model

**Comment by cerisue15** [comment]
<img width="1444" alt="Screen Shot 2019-11-20 at 9 19 39 AM" src="https://user-images.githubusercontent.com/55829559/69246559-ef79ba00-0b76-11ea-843f-d8fcb9e389e6.png">

<img width="1447" alt="Screen Shot 2019-11-20 at 10 16 26 AM" src="https://user-images.githubusercontent.com/55829559/69251108-e1c83280-0b7e-11ea-85c0-f23989924f2f.png">

<p> created the heroku account an deployed our app. I also added the data models to the parse-dashboard.
